
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND CONTAINS DIFF EXCLUDE GET INTERSECT NAME OR UNION URLexpression : GET URL\n    | GET URL instructioninstruction : contrainte UNION contrainte\n    | instruction INTERSECT contrainte\n    | instruction DIFF contrainte\n    | instruction OR contrainte\n    | instruction AND contrainte\n    | contraintecontrainte : CONTAINS NAME\n    | EXCLUDE NAME'
    
_lr_action_items = {'GET':([0,],[2,]),'$end':([1,3,4,5,13,14,15,16,17,18,19,],[0,-1,-2,-8,-9,-10,-4,-5,-6,-7,-3,]),'URL':([2,],[3,]),'CONTAINS':([3,8,9,10,11,12,],[6,6,6,6,6,6,]),'EXCLUDE':([3,8,9,10,11,12,],[7,7,7,7,7,7,]),'INTERSECT':([4,5,13,14,15,16,17,18,19,],[8,-8,-9,-10,-4,-5,-6,-7,-3,]),'DIFF':([4,5,13,14,15,16,17,18,19,],[9,-8,-9,-10,-4,-5,-6,-7,-3,]),'OR':([4,5,13,14,15,16,17,18,19,],[10,-8,-9,-10,-4,-5,-6,-7,-3,]),'AND':([4,5,13,14,15,16,17,18,19,],[11,-8,-9,-10,-4,-5,-6,-7,-3,]),'UNION':([5,13,14,],[12,-9,-10,]),'NAME':([6,7,],[13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'instruction':([3,],[4,]),'contrainte':([3,8,9,10,11,12,],[5,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> GET URL','expression',2,'p_expression','idule.py',45),
  ('expression -> GET URL instruction','expression',3,'p_expression','idule.py',46),
  ('instruction -> contrainte UNION contrainte','instruction',3,'p_instruction','idule.py',49),
  ('instruction -> instruction INTERSECT contrainte','instruction',3,'p_instruction','idule.py',50),
  ('instruction -> instruction DIFF contrainte','instruction',3,'p_instruction','idule.py',51),
  ('instruction -> instruction OR contrainte','instruction',3,'p_instruction','idule.py',52),
  ('instruction -> instruction AND contrainte','instruction',3,'p_instruction','idule.py',53),
  ('instruction -> contrainte','instruction',1,'p_instruction','idule.py',54),
  ('contrainte -> CONTAINS NAME','contrainte',2,'p_contrainte','idule.py',57),
  ('contrainte -> EXCLUDE NAME','contrainte',2,'p_contrainte','idule.py',58),
]
